(pk "hello-world!")
(pk (current-module))
(use-modules (emacs))
(pk emacs-env)
;; (define (emacs-funcall name . args)
;;   (%emacs-funcall (emacs-env-ptr emacs-env)
;;                   (symbol->string name)
;;                   (length args)
;;                   args))
;; (emacs-funcall 'list-)
